# Generated by Django 5.0 on 2023-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadPhotoTest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='picture',
            field=models.ImageField(upload_to='cars/'),
        ),
    ]
